name: test

on:
  workflow_dispatch:
    inputs:
      msName:
        type: choice
        required: true
        description: microservice to deploy
        options: 
        - odd
        - even

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        env:
            PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            HOSTNAME: ${{secrets.SSH_HOST}}
            GH_TOKEN: ${{ github.token }}
            USER_NAME: ${{secrets.USER_NAME}}
            NAMESAPCE: stage
        run: |
          gh cache list
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
              helm repo add roy https://royta1.github.io/test
              helm repo update --force
              helm search repo
              '